#!/bin/bash

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_DISABLE_RPROMPT=true

POWERLEVEL9K_DIR_HOME_BACKGROUND='black'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='black'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='black'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='077'

POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='210'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='221'

POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

POWERLEVEL9K_CUSTOM_JAVASCRIPT="echo -n '\uf121  \ue30d  & \ufa93'"
POWERLEVEL9K_CUSTOM_JAVASCRIPT_BACKGROUND='black'
POWERLEVEL9K_CUSTOM_JAVASCRIPT_FOREGROUND='210'

POWERLEVEL9K_CUSTOM_1="echo -n '\uf121'"
POWERLEVEL9K_CUSTOM_1_BACKGROUND='black'
POWERLEVEL9K_CUSTOM_1_FOREGROUND='084'

POWERLEVEL9K_CUSTOM_2="echo -n '\ue30d'"
POWERLEVEL9K_CUSTOM_2_BACKGROUND='black'
POWERLEVEL9K_CUSTOM_2_FOREGROUND='085'

POWERLEVEL9K_CUSTOM_3="echo -n '&'"
POWERLEVEL9K_CUSTOM_3_BACKGROUND='black'
POWERLEVEL9K_CUSTOM_3_FOREGROUND='086'

POWERLEVEL9K_CUSTOM_4="echo -n '\ufa93'"
POWERLEVEL9K_CUSTOM_4_BACKGROUND='black'
POWERLEVEL9K_CUSTOM_4_FOREGROUND='087'

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0b0'

# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_javascript dir vcs)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_1 custom_2 custom_3 custom_4 dir vcs)
