#!/usr/bin/env bash

# ANSI color scheme script featuring Space Invaders

# Original: http://crunchbanglinux.org/forums/post/126921/#p126921
# Modified by lolilolicon

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
bld=$'\e[1m'
rst=$'\e[0m'


printf "
 $f1  ▀▄   ▄▀     $f2 ▄▄▄████▄▄▄    $f3  ▄██▄     $f4  ▀▄   ▄▀     $f5 ▄▄▄████▄▄▄    $f6  ▄██▄  $rst
 $f1 ▄█▀███▀█▄    $f2███▀▀██▀▀███   $f3▄█▀██▀█▄   $f4 ▄█▀███▀█▄    $f5███▀▀██▀▀███   $f6▄█▀██▀█▄$rst
 $f1█▀███████▀█   $f2▀▀███▀▀███▀▀   $f3▀█▀██▀█▀   $f4█▀███████▀█   $f5▀▀███▀▀███▀▀   $f6▀█▀██▀█▀$rst
 $f1▀ ▀▄▄ ▄▄▀ ▀   $f2 ▀█▄ ▀▀ ▄█▀    $f3▀▄    ▄▀   $f4▀ ▀▄▄ ▄▄▀ ▀   $f5 ▀█▄ ▀▀ ▄█▀    $f6▀▄    ▄▀$rst

 \e[91m▄ ▀▄   ▄▀ ▄   \e[92m ▄▄▄████▄▄▄    \e[93m  ▄██▄     \e[94m▄ ▀▄   ▄▀ ▄   \e[95m ▄▄▄████▄▄▄    \e[96m  ▄██▄  $rst
 \e[91m█▄█▀███▀█▄█   \e[92m███▀▀██▀▀███   \e[93m▄█▀██▀█▄   \e[94m█▄█▀███▀█▄█   \e[95m███▀▀██▀▀███   \e[96m▄█▀██▀█▄$rst
 \e[91m▀█████████▀   \e[92m▀▀▀██▀▀██▀▀▀   \e[93m▀▀█▀▀█▀▀   \e[94m▀█████████▀   \e[95m▀▀▀██▀▀██▀▀▀   \e[96m▀▀█▀▀█▀▀$rst
 \e[91m ▄▀     ▀▄    \e[92m▄▄▀▀ ▀▀ ▀▀▄▄   \e[93m▄▀▄▀▀▄▀▄   \e[94m ▄▀     ▀▄    \e[95m▄▄▀▀ ▀▀ ▀▀▄▄   \e[96m▄▀▄▀▀▄▀▄$rst


                                     $f7▌$rst

                                   $f7▌$rst

                              $f7    ▄█▄    $rst
                              $f7▄█████████▄$rst
                              $f7▀▀▀▀▀▀▀▀▀▀▀$rst
"
